// src/views/CodeEditor.vue
<template>
	<div v-if="loading && firstLoad" class="absolute-center">
		<v-progress-circular :size="70" color="green" indeterminate/>
		<p>Loading...</p>
	</div>
	<div v-else>
		<div class="header">
			<h1>{{ data.title }}</h1>
		</div>
		<div class="code-zone">
			<div class="code-zone--left">
				<div class="container container--rounded container--description">
					<h2>Task</h2>
					<v-divider/>
					{{ data.description }}
				</div>
				<div class="container container--rounded container--output">
					<div style="display: flex;">
						<h2>Output</h2>
						<div style="margin-right: 1rem; margin-left: auto; vertical-align: baseline;" v-html="runText"></div>
					</div>
					<v-divider/>
					<pre v-if="outputText">{{ outputText }}</pre>
				</div>
				<div class="container container--rounded container--stats">
					<h2>Stats</h2>
					<v-divider/>
					<v-table>
						<thead>
						<tr>
							<th class="text-left">
								Execution Time
							</th>
							<th class="text-left">
								Memory Usage
							</th>
						</tr>
						</thead>
						<tbody>
						<tr v-if="execTime">
							<td>{{ execTime }} ms</td>
							<td>{{ maxMemory }} kb</td>
						</tr>
						</tbody>
					</v-table>
				</div>
			</div>
			<div class="code-editor" style="margin-right: 1rem">
				<div class="code-tool-bar">
					<v-select
						:item-value="selectedLanguage"
						:items="languages"
						:model-value="selectedLanguage"
						label="Language"
						return-object
						variant="plain"
						@update:modelValue="setSelection"
					></v-select>
					<div style="margin-right: 0; margin-left: auto;"/>
					<v-btn prepend @click="reset">
						<v-icon>mdi-content-save</v-icon>
						Save prgress
					</v-btn>
					<v-btn prepend @click="reset">
						<v-icon>mdi-refresh</v-icon>
						Reset
					</v-btn>
					<v-btn v-if="true" color="success" @click="onRunCodeClick">
						<v-progress-circular v-if="evalLoading" :size="20" color="white" indeterminate
						                     style="margin-right: 5px"/>
						<v-icon v-else style="margin-right: 5px">mdi-play</v-icon>
						Run Code
					</v-btn>
					<v-btn v-else prepend>
						<v-icon>mdi-content-save</v-icon>
						Save solution
					</v-btn>
				</div>
				<MonacoEditor
					v-model:value="data.starterCode"
					:language="monacoLanguage"
					:theme="theme"
					height="50%"
				></MonacoEditor>
				<div class="container">

				</div>
				<div class="code-tool-bar">
					<h2>Test code</h2>
				</div>
				<v-divider/>
				<MonacoEditor
					v-model:value="data.testCode"
					:language="monacoLanguage"
					:theme="theme"
					height="31%"
					@change="change"
				></MonacoEditor>
				<div class="container"/>
			</div>
		</div>
	</div>
</template>

<script lang="ts" setup>
import {computed, reactive, ref, watch} from "vue";
import MonacoEditor from "monaco-editor-vue3";
import {useQuery} from "@vue/apollo-composable";
import gql from "graphql-tag";
import type {CodeResponse, ProgrammingTask, Stat} from "@/gql/types/graphql";
import {useRoute} from 'vue-router'


let originalTestCode = "";
let originalCode = "";

//region Reactive variables
const route = useRoute();

const props = reactive({
	id: parseInt(route.params["id"] as string),
	language: "default"
});

const evaluateProps = {
	code: "",
	language: ""
};

const evaluateOptions = ref({
	enabled: false
});

const data = ref<ProgrammingTask>({
	id: -1,
	description: "",
	starterCode: "",
	title: "",
	testCode: "",
	language: ""
});

const firstLoad = ref(true);

const languages = ref([
	"loading..."
]);

const selectedLanguage = ref("default");
//endregion

// region Graphql
const {result, error, loading} = useQuery<{ programmingTask: ProgrammingTask }>(gql`
query GetCode($id:Int!, $language:String!) {
  programmingTask(taskId: $id, language: $language) {
    title
    description
    starterCode
    testCode
    language
    availableLanguages
  }
}
`, props);

const {
	result: evalResult,
	error: evalError,
	loading: evalLoading,
	refetch: evaluateCode
} = useQuery<{ evaluate: CodeResponse }>(gql`
query Evaluate($code:String!, $language:String!) {
  evaluate(code:$code,language:$language,taskId:1) {
    output
    stats {
      mem
    }
    errorText
    isSuccessful
    executionTimeMS
  }
}
`, evaluateProps, evaluateOptions);
// endregion

// region Computed variables
const monacoLanguage = computed(() => {
	// Map languages to the monaco editors language
	switch (selectedLanguage.value) {
		case "C#":
			return "csharp";
		default: // If they don't need overriding then allow it
			return selectedLanguage.value.toLowerCase();
	}
});

const maxMemory = computed(() => Math.round(evalResult.value?.evaluate.stats.reduce((acc: number, val: Stat) => val.mem > acc ? val.mem : acc, 0) / 1000))
const execTime = computed(() => evalResult.value?.evaluate.executionTimeMS);
const runText = computed(() => {
	if (evalResult.value == undefined) return;
	if (evalResult.value?.evaluate.errorText) {
		return `<span style="color: red;">Build error</span>`;
	}
	if (!evalResult.value?.evaluate.isSuccessful) {
		return `<span style="color: red;">Failing Tests</span>`;
	}
	return `<span style="color: green;">Passing Tests</span>`;
})

const outputText = computed(() => {
	if (evalResult.value == undefined) return;
	if (evalResult.value?.evaluate.errorText) {
		return evalResult.value?.evaluate.errorText;
	}
	return evalResult.value?.evaluate.output;
})
watch(result, () => {
	if (props.language == "default") {
		// If we're getting the default language for the task, update the drop-down's value
	}
	originalTestCode = result.value?.programmingTask.testCode;
	originalCode = result.value?.programmingTask.starterCode;
	data.value = result.value?.programmingTask;
	languages.value = result.value?.programmingTask.availableLanguages
	selectedLanguage.value = result.value?.programmingTask.language;
});

watch(evalResult, console.log)
watch(evalError, console.log)

watch(error, () => {
	console.log(error)
});

watch(loading, () => {
	if (!loading.value) {
		firstLoad.value = false;
	}
})

// endregion

const theme = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? "vs-dark" : "vs"


// region Functions
function setSelection(e: string) {
	props.language = e;
}

function change() {
	data.testCode = originalTestCode;
}

function onRunCodeClick() {
	evaluateProps.language = data.value.language;
	evaluateProps.code = data.value.starterCode;
	evaluateOptions.value.enabled = true;
	console.log(evaluateProps)
	evaluateCode(evaluateProps);
}

function reset() {
	data.value.starterCode = originalCode;
}

//endregion

</script>

<style scoped>
.header {
	height: 52px;
	border-bottom: 2px solid var(--color-border);
	margin-bottom: 8px;
}

.code-tool-bar {
	background-color: var(--color-background-hard);
	width: 100%;
	display: flex;
	flex-direction: row;
	padding: 0.5rem 0.5rem 0.5rem 2rem;
	border-radius: 15px 15px 0 0;
}

.code-tool-bar .v-input {
	max-width: 200px;
}

.code-zone {
	width: calc(100vw - 60px);
	height: calc(100vh - 60px);
	display: grid;
	grid-template-columns: 40% 60%;
}

.code-editor {
	display: flex;
	flex-direction: column;
}

.container {
	background-color: var(--color-background-hard);
	border-radius: 0 0 15px 15px;
	margin: 0 0 1rem 0;
	flex-direction: row;
	padding: 1rem;
}

.container--rounded {
	border-radius: 15px;
	margin: 0 1rem 1rem 1rem;
}

.container--description {
	height: 40%;
	overflow: scroll;
	flex-direction: column;
}

.container--output {
	height: 40%;
	overflow: scroll;
	flex-direction: column;
}

.container--stats {
	height: 20%;
	flex-direction: column;
	overflow: scroll;
}

.code-zone--left {
	display: flex;
	flex-direction: column;
}

button {
	margin-right: 0.5rem;
}

pre {
	white-space: pre-wrap;
}
</style>

// src/pages/CodeEditor/CodeEditor.tsx
import { useLazyQuery, useMutation, useQuery } from "@apollo/client";
import CircularProgress from "@mui/material/CircularProgress";
import Select, { SelectChangeEvent } from "@mui/material/Select";
import InputLabel from "@mui/material/InputLabel";
import React from "react";
import { useNavigate, useParams } from "react-router-dom";
import Monaco from "../../components/Monaco";
import { graphql } from "../../gql";
import "./CodeEditor.tsx.css";
import MenuItem from "@mui/material/MenuItem";
import FormControl from "@mui/material/FormControl";
import Paper from "@mui/material/Paper";
import Button from "@mui/material/Button";
import { CodeResponse, ProgrammingTask, Stat } from "../../gql/graphql";
import { unauthorisedCheck } from "../../gql/exceptionChecks";
import UserContext from "../../contexts/UserContext";
import Divider from "@mui/material/Divider";
import RefreshIcon from "@mui/icons-material/Refresh";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import LoadingButton from "@mui/lab/LoadingButton";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import TableCell from "@mui/material/TableCell";
import ErrorIcon from "@mui/icons-material/Error";
import CloudSyncIcon from "@mui/icons-material/CloudSync";
import SaveIcon from "@mui/icons-material/Save";
import SaveAltIcon from "@mui/icons-material/SaveAlt";

enum SaveState {
  SAVING,
  UNSAVED,
  SAVED,
}

const Indicator: React.FC<{ saveState: SaveState }> = (props) => {
  switch (props.saveState) {
    case SaveState.UNSAVED:
      return (
        <div className="inline">
          <ErrorIcon style={{ margin: "auto" }} />
          <p className="info">You have unsaved changes</p>
        </div>
      );

    case SaveState.SAVING:
      return (
        <div className="inline">
          <CloudSyncIcon style={{ margin: "auto" }} />
          <p className="info">Saving changes...</p>
        </div>
      );

    case SaveState.SAVED:
      return (
        <div className="inline">
          <SaveIcon style={{ margin: "auto" }} />
          <p className="info">Solution Saved</p>
        </div>
      );

    default:
      return (
        <div className="inline">
          <ErrorIcon style={{ margin: "auto" }} />
          <p className="info">You have unsaved changes</p>
        </div>
      );
  }
};

interface IToolBarProps {
  language: string;
  avalibleLanguages: Array<string>;
  handleChange: (language: string) => void;
  handleReset: () => void;
  handleRun: () => void;
  handleSubmit: () => void;
  runCodeIsLoading: boolean;
  saveState: SaveState;
  canSubmit: boolean;
}

const ToolBar: React.FC<IToolBarProps> = (props) => {
  function handleChange(evt: SelectChangeEvent) {
    props.handleChange(evt.target.value);
  }

  return (
    <div className="code-tool-bar">
      <h2>Editor</h2>
      <FormControl style={{ minWidth: "200px" }}>
        <InputLabel id="language-select-label">Language</InputLabel>
        <Select
          labelId="language-select-label"
          id="language-select"
          label="Language"
          onChange={handleChange}
          value={props.language}
        >
          {props.avalibleLanguages.map((language) => (
            <MenuItem
              id={`language-select-${language.replace("#", "sharp")}`}
              value={language}
            >
              {language}
            </MenuItem>
          ))}
        </Select>
      </FormControl>
      <Indicator saveState={props.saveState} />
      <div style={{ margin: "auto 0 auto auto" }}>
        <Button
          id="reset-solution"
          style={{ marginRight: "1rem" }}
          color="secondary"
          startIcon={<RefreshIcon />}
          variant="contained"
          onClick={props.handleReset}
        >
          Reset
        </Button>
        {props.canSubmit && (
          <LoadingButton
            style={{ marginRight: "1rem" }}
            loading={props.runCodeIsLoading}
            loadingPosition="start"
            color="success"
            startIcon={<SaveAltIcon />}
            variant="contained"
            onClick={props.handleSubmit}
          >
            Submit Code
          </LoadingButton>
        )}
        {!props.canSubmit && (
          <LoadingButton
            id="run-code"
            style={{ marginRight: "1rem" }}
            loading={props.runCodeIsLoading}
            loadingPosition="start"
            color="success"
            startIcon={<PlayArrowIcon />}
            variant="contained"
            onClick={props.handleRun}
          >
            Run Code
          </LoadingButton>
        )}
      </div>
    </div>
  );
};

const Stats: React.FC<{ data: CodeResponse | undefined }> = (props) => {
  if (!props.data) {
    return (
      <Paper className="container container--stats">
        <h2>Stats</h2>
        <Divider />
      </Paper>
    );
  }

  let max = props.data.stats.reduce((acc: number, val: Stat | null) => {
    if (val == null) {
      return acc;
    }
    return +val.mem > acc ? +val.mem : acc;
  }, 0);

  const maxMemory = Math.round(max / 1000);

  return (
    <Paper className="container container--stats">
      <h2>Stats</h2>
      <Divider />
      <Table>
        <TableHead>
          <TableRow>
            <TableCell align="left">Execution Time</TableCell>
            <TableCell align="left">Memory Usage</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          <TableRow>
            <TableCell>{props.data.executionTimeMS} ms</TableCell>
            <TableCell>{maxMemory} kb</TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </Paper>
  );
};

const getCode = graphql(`
  query getCode($id: Int!, $language: String!) {
    programmingTask(taskId: $id, language: $language) {
      id
      title
      description
      starterCode
      testCode
      language
      availableLanguages
      myCode
    }
  }
`);

const evaluateQuery = graphql(`
  query Evaluate($code: String!, $language: String!) {
    evaluate(code: $code, language: $language, taskId: 1) {
      output
      stats {
        mem
        cpu
      }
      errorText
      isSuccessful
      executionTimeMS
    }
  }
`);

const saveCode = graphql(`
  mutation SaveCode($submission: UserCodeSubmissionInput) {
    submitCode(submission: $submission)
  }
`);

const CodeEditor: React.FC = () => {
  // Params
  const params = useParams();
  const navigate = useNavigate();
  const userObserver = React.useContext(UserContext);

  // State
  const [selectedLanguage, setSelectedLanguage] = React.useState("default");
  const [task, setTask] = React.useState<ProgrammingTask | null>(null);
  const [outputClassName, setOttputClassName] = React.useState(
    "container container--output output"
  );
  const [timeout, updateTimeout] = React.useState<number | undefined>();
  const [saveState, setSaveState] = React.useState(SaveState.SAVED);
  const [canSubmit, setCanSubmit] = React.useState(false);
  const [skipChange, setSkipChange] = React.useState(false);
  // Ensure that we have a task id
  const taskId = parseInt(params.taskid ?? "-1");
  if (taskId === -1) {
    navigate("/modules");
  }

  // GraphQL
  const { data: getCodeData, error: getCodeError } = useQuery(getCode, {
    variables: {
      id: taskId,
      language: selectedLanguage,
    },
  });

  const [
    evaluate,
    { data: evaluateData, error: evaluateError, loading: evaluateLoading },
  ] = useLazyQuery(evaluateQuery, { fetchPolicy: "no-cache" });

  const [save, { loading: saveLoading }] = useMutation(saveCode);

  React.useEffect(() => {
    if (evaluateLoading) return;
    if (!evaluateData) return;
    if (evaluateData?.evaluate.isSuccessful) {
      setOttputClassName("container container--output output output--success");
      setCanSubmit(true);
    } else {
      setOttputClassName("container container--output output output--failure");
    }

    const timeout = setTimeout(() => {
      setOttputClassName("container container--output output");
    }, 1000);

    return function () {
      clearTimeout(timeout);
    };
  }, [evaluateData, evaluateLoading]);

  React.useEffect(() => {
    if (getCodeData) {
      if (selectedLanguage === "default") {
        setSelectedLanguage(getCodeData.programmingTask.language);
      }
      setTask(getCodeData.programmingTask);
    }
  }, [getCodeData]);

  React.useEffect(() => {
    unauthorisedCheck(getCodeError, userObserver);
  }, [getCodeError, userObserver]);

  React.useEffect(() => {
    if (saveLoading) {
      setSaveState(SaveState.SAVING);
    } else {
      setSaveState(SaveState.SAVED);
    }
  }, [saveLoading]);

  if (task === null) {
    return (
      <div
        style={{
          display: "grid",
          placeItems: "center",
          width: "100%",
          height: "100%",
        }}
      >
        <CircularProgress id="spinner" />
      </div>
    );
  }

  function evaluateCode() {
    if (!task) return; // Task should never be null if we have a task to run...
    evaluate({
      variables: {
        code: task.myCode,
        language: selectedLanguage,
      },
    });
  }

  function handleSubmit() {}

  function onCodeUpdated(code: string) {
    // If they could previously submit, but they've changed some code, disable it again
    if (skipChange) {
      setSkipChange(false);
    }
    if (canSubmit) {
      setCanSubmit(false);
    }
    setTask((previous) => {
      return { ...previous, myCode: code } as ProgrammingTask;
    });
    clearTimeout(timeout);
    setSaveState(SaveState.UNSAVED);

    const t1 = setTimeout(() => {
      save({
        variables: {
          submission: {
            codeText: code,
            taskId,
            language: selectedLanguage,
          },
        },
      });
    }, 1000) as unknown as number;
    updateTimeout(t1);
  }

  return (
    <div className="code-zone">
      <div className="code-editor">
        <Paper style={{ height: "50%" }}>
          <ToolBar
            avalibleLanguages={task.availableLanguages as string[]} // CodeGen isn't seeing that this isn't an optional
            language={selectedLanguage}
            handleChange={(x) => {
              setSkipChange(true);
              setSelectedLanguage(x);
            }}
            handleReset={() => {
              setTask({ ...task, myCode: task.starterCode });
            }}
            handleRun={evaluateCode}
            handleSubmit={handleSubmit}
            saveState={saveState}
            runCodeIsLoading={evaluateLoading}
            canSubmit={canSubmit}
          />
          <Monaco
            codeText={task.myCode!}
            height="90%"
            language={selectedLanguage}
            editable
            onChange={onCodeUpdated}
          />
        </Paper>
        <Paper style={{ height: "44%", marginTop: "1rem" }}>
          <div className="code-tool-bar">
            <h2>Tests</h2>
          </div>
          <Monaco
            editable={false}
            codeText={task.testCode}
            height="100%"
            language={selectedLanguage}
          />
        </Paper>
        <div style={{ height: "10px" }} />
      </div>
      <div className="code-zone--right">
        <Paper className="container container--description">
          <h2>Task</h2>
          <Divider />
          {task.description}
        </Paper>
        <Paper className={outputClassName}>
          <div style={{ display: "flex" }}>
            <h2>Output</h2>
            <div
              style={{
                marginRight: "1rem",
                marginLeft: "auto",
                verticalAlign: "baseline",
              }}
            >
              {}
            </div>
          </div>
          <Divider />
          <pre>{evaluateData?.evaluate.output}</pre>
        </Paper>
        <Stats data={evaluateData?.evaluate} />
      </div>
    </div>
  );
};

export default CodeEditor;
